# Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.

def nearly_equal(a, b):
    # Case 1: substitution
    if len(a) == len(b):
        return sum(x != y for x, y in zip(a, b)) == 1

    # Case 2: insertion or deletion
    if abs(len(a) - len(b)) == 1:
        # always make a the longer one
        if len(a) < len(b):
            a, b = b, a

        # remove one char from a and compare
        for i in range(len(a)):
            if a[:i] + a[i+1:] == b:
                return True

    return False


# Read from user
a = input("Enter first string: ")
b = input("Enter second string: ")

print(nearly_equal(a, b))
